# Generated by Django 3.0.8 on 2020-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(max_length=10, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.BigIntegerField(max_length=6)),
            ],
        ),
    ]
