# Generated by Django 3.0.8 on 2020-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
