# Generated by Django 3.0.8 on 2020-07-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
